---
- name: Restart Jenkins, if necessary
  meta: flush_handlers

- name: Install dependencies
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - python
      - python-jenkins
      - ca-certificates
      - python2-pip
      - ansible
      - mlocate
      - tree
      - git

# need latest versions for installing Jenkins plugins - otherwise get a certificate error
- name: CA-Certificates update command line execution
  command: /bin/update-ca-trust

- name: Force upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

# http://stackoverflow.com/a/34522653
- name: Wait until Jenkins web interface is available
  wait_for: "host={{ jenkins_hostname }} port={{ jenkins_http_port }} state=present delay=5 timeout=300"

- name: Wait until Jenkins web interface is ready
  command: 'curl -s -o /dev/null -w "%{http_code}" http://{{ jenkins_hostname }}:{{ jenkins_http_port}}/cli/'
  register: result
  until: 'result.stdout[0] in ["2", "3"]' # 2xx or 3xx status code
  retries: 50
  delay: 3
  changed_when: false
