---
- name: Restart Jenkins, if necessary
  meta: flush_handlers

- name: Install dependencies
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - python
      - python-jenkins
      - python-pip
      - ansible
      - mlocate
      - tree
      - git

- name: Force upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

# http://stackoverflow.com/a/34522653/358804
- name: Wait for Jenkins to be available
  uri:
    url: http://{{ jenkins_hostname }}:{{ jenkins_http_port }}
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
