Vagrant.configure("2") do | config |
  config.vm.box = "dummy"

  config.vm.provider :aws do | aws, override |
    aws.aws_dir     = ENV['HOME'] + "/.aws/"
    aws.aws_profile = "GEHC-000"
    aws.ami         = "ami-a8d369c0"

    override.ssh.username = "ec2-user"
  end
end
